[package]
name = "hashassin_server"
version = "0.1.0"
edition = "2024"

[dependencies]
hashassin_core = { path = "../core" }
tracing = "0.1"
stretto = "0.8"
tokio = { version = "1", features = ["full"] }